version: '1.0'

server:
  port: 3000
  rateLimit:
    window: 60000
    max: 100

settings:
  proof: none
  plugins:
    - source: ../../plugins/logger.ts
      timeout: 5000

apis:
  - name: MockAPI
    url: http://localhost:5123
    endpoints:
      - name: getValue
        path: /value
        encoding:
          type: int256
          path: $.value
